### PR TITLE
Generate meta tags

### PR DESCRIPTION
**Pull request by doug-wade**
Adds example meta tags to the generated hello world page

### CODE REVIEW

**Comment by gigabo** [comment]
LGTM

**Comment by doug-wade** [comment]
Based on https://github.com/joshbuchea/HEAD

**Comment by gigabo** [comment]
Even better. :)

**Comment by gigabo** [comment]
@doug-wade - You want to try to get this in for `0.3.0`?

Looking to cut a (hopefully) final beta with changes from master this afternoon.

**Pull request merged**
