### PR TITLE
add missing dependencies to react-server-cli

### LINKED ISSUE #971: react-server fails to start on fresh setup
Hi, 

On OSX with node `v7.7.4`, fresh setup of react-server project fails to start.

```
$ react-server init
No package.json found.  Running `npm init --yes`
Wrote to /Users/myhome/Projects/sample/package.json:

{
  "name": "sample",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Installing dependencies

$ react-server add-page '/' Homepage
Generating pages/Homepage.js
Updating routes.json
All set!

$ react-server start
{ Error: Cannot find module 'express-state'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/myhome/.nvm/versions/node/v7.7.4/lib/node_modules/react-server-cli/target/commands/start.js:65:21)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/myhome/.nvm/versions/node/v7.7.4/lib/node_modules/react-server-cli/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
```

### PR DESCRIPTION
**Pull request by mcskinner**
This is intended to fix #971, which can be patched manually via global install of the missing packages. Of course my local environment is now tainted by the global dependency installs, so I'm not entirely sure how I should go about testing this (advice appreciated).

The dependency versions are copied over from react-server, but I know next to nothing about package versioning best practices. I'm willing to be scolded and then corrected for choosing poorly.

### CODE REVIEW

**Comment by hatfarm** [comment]
I also had to add `serialize-javascript` to get it to start up.

**Comment by mcskinner** [comment]
guess this project is on low maintenance mode...

**Comment by roblg** [comment]
Thanks @mcskinner! Sorry for the slow turnaround.

**Comment by mcskinner** [comment]
@roblg no problem, sorry for the snark haha :)

**Pull request merged**
