### PR TITLE
Added more text to the README on the motivations behind react-server

### PR DESCRIPTION
**Pull request by aickin**
I think that the main README could benefit from more high-level information on what react-server is and what it's good for (or at least, what it's trying to be good for :grinning:), so I wrote a draft. My goal was to let folks arriving at the github project page more quickly grok what `react-server` is about.

Edits are **more** than welcome.

### CODE REVIEW

**Comment by roblg** [comment]
LGTM 👍

**Comment by gigabo** [comment]
Thanks @aickin! 👍

**Comment by gigabo** [comment]
I wonder if any of this should go into `packages/react-server/README.md`, too, so it shows up on npmjs.com?

**Comment by aickin** [comment]
Sure, I can take a swing at it.

**Pull request merged**
