### PR TITLE
Migrate back to Lerna :tada:

### PR DESCRIPTION
**Pull request by gigabo**
Lerna supports hoisting now, so I think we're all set to migrate back.

### CODE REVIEW

**Comment by drewpc** [comment]
Sweet!  Looks like there's still some [asini references](https://github.com/redfin/react-server/search?p=1&q=asini&utf8=✓) in the codebase: `.gitignore` and some `react-server-website` references.  Do those need to be changed as well?

**Comment by gigabo** [comment]
Oh, nice catch on the `.gitignore`.  Didn't check hidden files.  Seems like no harm in leaving it?

The website references are actually for the Asini slackin site, which we're keeping up for now.

**Comment by gigabo** [comment]
Any objections here?  Users are [running into issues](https://github.com/asini/asini/issues/82) that [have already been fixed](https://github.com/lerna/lerna/pull/586) on Lerna.

**Comment by drewpc** [comment]
Conceptually, I'm all for it.  Practically, however, I obstain on this one because I don't know enough about either lerna or asini to provide any insight.

**Comment by gigabo** [comment]
@drewpc That's fair.  Asini's dead, though, so it's a matter of getting back onto a tool that's maintained.

Gonna merge this.  You'll need to `npm i` again when you pull it, but other than that it should be a seamless transition. 🤞 

Let me know if you run into any trouble!

**Pull request merged**
