### PR TITLE
Don't require node 6 to run react-server-cli

### PR DESCRIPTION
**Pull request by lidawang**
cc @gigabo

### CODE REVIEW

**Comment by gigabo** [comment]
Thanks @lidawang!  Will be nice to pick up https://github.com/lerna/lerna/pull/192 when it lands so we can drop the extra two copies of `cli.js` here. 😛

**Comment by doug-wade** [comment]
This seems like its going backwards to me.  Node 4 supports destructuring, but its behind a flag; can you try adding the `--harmony_destructuring` flag to https://github.com/redfin/react-server/blob/master/packages/react-server-cli/bin/react-server-cli#L1, rather than removing the destructuring?  I don't think we want to try to support node < 4.

**Comment by gigabo** [comment]
@doug-wade - This is actually just the top-most entry point for `react-server-cli`.  We have a couple of extra copies laying around until the next version of Lerna lands, but after that it will just be this one tiny file that needs this treatment. :)

**Comment by doug-wade** [comment]
@gigabo oh, I see.  sorry @lidawang, lgtm 👍

**Pull request merged**
