### PR TITLE
Add merging prs policy

### PR DESCRIPTION
**Pull request by doug-wade**
I was chatting with everyday super hero @gigabo in Slack just now, and we thought it might make sense to document a policy around what's required to merge a pr.  Here's a quick first draft; let's make sure to get this one right so we are inclusive without risking instability.

### CODE REVIEW

**Comment by gigabo** [comment]
This makes sense to me.  One approval and someone _else_ merges.

@roblg, @sresant what do you think?  Anyone else?

**Comment by gigabo** [comment]
What about for PRs _submitted by maintainers?_  Still two additional sign-offs?

**Comment by gigabo** [comment]
BTW - I turned on branch protection for `master` and made reviews required.

image

Wondering if the two-sign-off requirement is too strict... 🤔

**Comment by sresant** [comment]
I am in support of this for the most part. I think we might want to have a stricter policy on breaking changes like that previous React 15 upgrade that we did not merge for the longest time. Maybe in that situation we should have a larger consensus, rather then just 1 maintainer. In general however for regular bug fixes and enhancements this makes sense and would take the load off the regular people doing the merging. I think we might want to add more documentation for the breaking changes aspect and provide a more strict policy for that. Additionally would be worth documenting how we do merging on this project.

**Comment by gigabo** [comment]
@sresant Good call on the merging thing.  Basically: `Squash and merge`. 😁

**Comment by roblg** [comment]
Not sure how detailed we want the guidance to be, but I could imagine that there are areas of the code base where we'd definitely prefer a _specific_ maintainer, e.g. the person who most recently made significant changes to that part of the code?

Thanks for writing this down @doug-wade. My strategy up until now has basically just been waiting for @gigabo to merge things. I hear that doesn't scale... :grin:

**Comment by doug-wade** [comment]
> What about for PRs submitted by maintainers? Still two additional sign-offs?

Oh, my intention was that any pr can be merged with approval from any two maintainers, regardless of who the author is.

**Comment by drewpc** [comment]
Maybe something like:

> Documentation changes and bug fixes that include automated tests can be merged by a single maintainer who is not the author.  All other changes must be approved and merged by two maintainers who are not the author.

That should encourage automated test development in combination with the squash + merge strategy?

**Comment by drewpc** [comment]
Sounds like this change is "good enough" for now.  I'll `squash && merge`

**Pull request merged**
