### PR TITLE
Document hasDocument option

### PR DESCRIPTION
**Pull request by feychou**
I also added a custom `404` example in bike-share.
This is the related issue #885

### CODE REVIEW

**Comment by gigabo** [comment]
Awesome!  Thanks @feychou!

**Comment by gigabo** [comment]
Looks like something weird happened with Travis.  It's stuck "waiting for status to be reported", and it's not even giving me a link to the build so I can re-start it. 😕

**Comment by feychou** [comment]
Odd, I was just wondering where the link is. Anyway I wrote something else in the docs, hope this triggers the build.

**Comment by gigabo** [comment]
Yep, that did the trick.  Thanks @feychou!

**Pull request merged**
