### PR TITLE
Fix #234 Add svg logo

### LINKED ISSUE #234: Lower-res logo just doesn't look as good
Maybe I'm imagining things, but ever since #208 the logo doesn't seem to look as clear.

@careylin - Is it all in my head?

### PR DESCRIPTION
**Pull request by doug-wade**
Fix #234

### CODE REVIEW

**Comment by gigabo** [comment]
Thanks for taking this on @doug-wade.  The image in the README seems not to be working?

image

**Comment by gigabo** [comment]
Also, BTW - What is the purpose of the `[XXX] ` commit message prefix?  Without a leading `#` it isn't recognized by github (or [other consumers](https://github.com/lerna/lerna-changelog) of the commit message).  Do you have something interpreting this?

**Comment by doug-wade** [comment]
@gigabo I didn't realize I needed the octothorpe

**Comment by gigabo** [comment]
Awesome!  Thanks @doug-wade!

**Pull request merged**
