### PR TITLE
[DO NOT MERGE] WIP: Port tests to selenium

### PR DESCRIPTION
**Pull request by aickin**
DO NOT MERGE; CHECKING TO TEST TRAVIS BUILD ONLY.

This is an experimental branch to port the integration tests to Selenium. It's not complete (only ported `HelloWorldSpec` and `TitleSpec`, and I'm only making a PR to see if I can get it to work with Travis.

### CODE REVIEW

**Comment by aickin** [comment]
Closing and reopening to rerun the build.

**Comment by aickin** [comment]
Opening to rerun the build.

**Comment by aickin** [comment]
Reopening to rerun the build.

**Comment by aickin** [comment]
Closing and reopening to see if test failure is intermittent, which it looks like to me.

**Comment by aickin** [comment]
Reopening to test.

**Comment by drewpc** [comment]
Can we merge this into a WIP branch for @aickin and close this PR?  Travis will still pickup builds on pushes to that [branch](https://travis-ci.org/redfin/react-server/branches) and it will cleanup the PR list.

**Comment by doug-wade** [comment]
@drewpc this pr's open, and its easy to set up travis to track your remote;  assuming @aickin doesn't touch this in the next couple of days, I'm down for just closing it -- it's unclear whether the WIP is worth the merge conflicts.

**Comment by drewpc** [comment]
@doug-wade sweet.  Closed!  It can easily be reopened if needed in the future.

**Pull request closed without merging**
