### PR TITLE
Documentation update: bullet list for express middlewares

### PR DESCRIPTION
**Pull request by feychou**
And links to npm packages as suggested [here](https://github.com/redfin/react-server/pull/812#discussion_r95263075)

### CODE REVIEW

**Comment by doug-wade** [comment]
@feychou you might wanna consider joining our slack channel so we can chat about changes and plans and stuff: https://slack.react-server.io/ (I only suggest it cuz I just went to slack you about why you closed this and then you weren't there :stuck_out_tongue:)

**Comment by gigabo** [comment]
Yes, I was just doing the same thing. 😁 

This is awesome!

**Comment by feychou** [comment]
@doug-wade @gigabo Sure! The reason why I closed this is that I noticed it listed old commits in my fork and I did not understand why since they have been merged, but now I suspect it is just because I merged the upstream master after all.

**Comment by gigabo** [comment]
Thanks @feychou!

**Pull request merged**
