### PR TITLE
Change title for home page

### PR DESCRIPTION
**Pull request by emecell**
To get more SEO traffic, we should adjust the title for what people
search for. Change recommended by Joe Lei.

### CODE REVIEW

**Comment by emecell** [comment]
Right now we're ranked #20 for when you search for "react server side rendering". Let's try to at least get onto the first page and hopefully top 5. We probably also want to explore adding some more content to our home page like companies using React Server and community stats.

**Comment by gigabo** [comment]
Nice, good idea!

**Comment by gigabo** [comment]
@davidalber This will require a re-deploy of the website. 👹

**Comment by davidalber** [comment]
Yeah, there are a couple other changes that are waiting for a deployment. I've been meaning to ask a question in #840 about how we feel about that, which I just did [here](https://github.com/redfin/react-server/issues/840#issuecomment-278827940).

**Pull request merged**
