### PR TITLE
Upgrade superagent to 1.8.4

### PR DESCRIPTION
**Pull request by doug-wade**
Pull in bug fixes from superagent, most notably the fix to [250](https://github.com/visionmedia/superagent/issues/250), which was released in [1.5.0](https://github.com/visionmedia/superagent/releases/tag/v1.5.0). I could upgrade to 2.2.0, but I'll save the major version bump for another day.

### CODE REVIEW

**Comment by gigabo** [comment]
Remind me why superagent is a peer dependency instead of a normal dependency?

**Comment by roblg** [comment]
> Remind me why superagent is a peer dependency instead of a normal dependency?

I think because we wanted to make sure it's a singleton. Internally, we're installing custom response parsers. If we added the ability to install custom response parsers via ReactServerAgent (do we have that? We have response plugins..?) then it maybe wouldn't matter.

**Comment by gigabo** [comment]
Yeah, I think we do everything through RSA... not dealing with superagent at all from outside?

Would be nice to eliminate the need for another explicit dep for node 6 users.

**Comment by doug-wade** [comment]
@roblg we can use `plugRequest` and `plugResponse` for that, yeah? https://github.com/redfin/react-server/blob/master/docs/guides/using-react-server-agent.md#extending-superagent

**Comment by gigabo** [comment]
Make https://github.com/redfin/react-server/issues/628.  Doesn't need to hold this up, I guess.

Though users will need to update their superagent deps when they upgrade to the next version of React Server...

**Comment by doug-wade** [comment]
@gigabo we'll see how far we get today -- I also opened #630

**Comment by roblg** [comment]
> we can use plugRequest and plugResponse for that, yeah?

I think `plugResponse` may actually be too late, but I found this: https://visionmedia.github.io/superagent/#parsing-response-bodies, which definitely wan't around when we were hacking things up initially, and should make our lives easier. :)

**Pull request merged**
