### PR TITLE
Remove Sasha's early 2015 data proposal

### LINKED ISSUE #121: Data proposal doc?
Is this still relevant?  Does it belong here?  Is it up to date?

https://github.com/redfin/react-server/blob/master/docs/data-proposal.md

### PR DESCRIPTION
**Pull request by gigabo**
This pains me, because it's a great doc with an overview of the problem and
the enviroment and a good explanation for where we went with data through most
of 2015.  But, it has gotten out of date and the _stores_ part of it actually
isn't discussing anything that's (currently) part of `react-server`.

This resolves #121.

### CODE REVIEW

**Comment by gigabo** [comment]
Anybody want to take a stab at salvaging the still-relevant topic overview here and putting it into a context that's up-to-date with current `react-server`?

Speak now before I nuke it. 😬

**Comment by doug-wade** [comment]
@gigabo you mean the "Key Concepts" portion?

**Comment by gigabo** [comment]
I was actually thinking more of the "Design Principles" section.

**Comment by doug-wade** [comment]
I'll rescue "design principles" in a separate pr.  lgtm 👍

**Pull request merged**
