### PR TITLE
Link to new logo in readme

### PR DESCRIPTION
**Pull request by careylin**
@doug-wade permalinked to the old logo, this links to the new logo

### CODE REVIEW

**Comment by gigabo** [comment]
Not loading right for me? 😕 

image

**Comment by careylin** [comment]
hmm, will investigate

**Comment by careylin** [comment]
Oh duh, @doug-wade already encountered this bug https://github.com/isaacs/github/issues/316 which is why he used the permalink >.<

**Comment by gigabo** [comment]
Yeah, looks awesome now! 🎉 

image

**Pull request merged**
