### PR TITLE
Fix react-server issue with npm2

### PR DESCRIPTION
**Pull request by sresant**
relates to [issue 662](https://github.com/redfin/react-server/issues/662)

### CODE REVIEW

**Comment by doug-wade** [comment]
:+1:

**Comment by gigabo** [comment]
@sresant Does this also get the CLI working in node 4 outside the repo?  Like, even when it's installed globally?

**Comment by gigabo** [comment]
@sresant Looks like this needs a rebase.  Does this plus #691 get everything working in node 4?  How about the superagent issue you were seeing?

**Comment by sresant** [comment]
@gigabo rebased and tested using node 4 and everything worked! And no superagent issue 😖

**Comment by gigabo** [comment]
Great, thanks @sresant.

**Comment by gigabo** [comment]
Wait... :squint:

This doesn't look like the right diff anymore.  Something go wrong with the rebase?

**Comment by gigabo** [comment]
That's better. 😌

**Pull request merged**
